spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${AUTH_POSTGRES_USER:your_db_user}
    password: ${AUTH_POSTGRES_PASSWORD:your_db_password}
    url: jdbc:postgresql://localhost:5432/${AUTH_POSTGRES_DB:your_db_name}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/YourRealm

keycloak:
  client-id: ${CLIENT_ID:your_client_id}
  client-secret: ${CLIENT_SECRET:your_client_secret}
  redirect-uri: http://localhost:8081/callback

server:
  port: 8081

